name: Pre-commit hooks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install the project
        run: uv sync --all-groups

      - name: Install pre-commit hooks
        run: uv run --no-sync pre-commit install

      - name: Run pre-commit on all files
        run: uv run --no-sync pre-commit run -a
