name: Pre-commit hooks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pre-commit hooks
        run: |
          pip install uv
          uv pip install -e .[dev]
          uv run pre-commit install

      - name: Run pre-commit on all files
        run: uv run pre-commit run --all-files
